services:
    scpi-invest-db:
      image: postgres
      container_name: scpi-invest-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      ports:
        - "5432:5432"