spring:
  webhook:
    username: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  kafka:
    bootstrap-servers: localhost:9094
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9100/realms/master
          jwk-set-uri: http://localhost:9100/realms/master/protocol/openid-connect/certs
logging:
  level:
    org.apache.kafka: ERROR
    kafka: ERROR
    org.springframework.kafka: ERROR