spring:
  application:
    name: scpi-invest-plus-api
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  spring:
    batch:
      jdbc:
        initialize-schema: always

    flyway:
      baseline-on-migrate: true









