spring:
  application:
    name: scpi-invest-plus-api
    version: 1.0.0
  webhook:
    username: admin
    password: admin
  datasource:
    url: jdbc:postgresql://scpi-invest-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    uris: http://elasticsearch:9200
    hostname: elasticsearch-batch.scpi-invest-plus-int
    port: 9200

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka-svc.kafka:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.check-consulting.net/realms/master
          jwk-set-uri: https://keycloak.check-consulting.net/realms/master/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true



keycloak:
  serverUrl: https://keycloak.check-consulting.net
  realm: master
  clientId: scpi-invest-plus
  adminUsername: admin
  adminPassword: admin





