apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: {{ .Chart.Name }}
data:
  SPRING_DATASOURCE_URL: "{{ .Values.database.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.database.username }}"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafka.bootstrapServers }}"
  SPRING_SECURITY_ISSUER_URI: "{{ .Values.security.oauth2.issuerUri }}"
  SPRING_SECURITY_JWK_URI: "{{ .Values.security.oauth2.jwkSetUri }}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "{{ .Values.jpa.hibernate.ddlAuto }}"
  SPRING_JPA_HIBERNATE_DIALECT: "{{ .Values.jpa.hibernate.dialect }}"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "{{ .Values.management.endpoints.web.exposure }}"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "{{ .Values.management.prometheus.enabled }}"
  MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED: "{{ .Values.management.prometheus.enabled }}"
