apiVersion: apps/v1
kind: Deployment
metadata:
  name: scpi-invest-plus-api
  labels:
    app: scpi-invest-plus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scpi-invest-plus-api
  template:
    metadata:
      name: scpi-invest-plus-api
      labels:
        app: scpi-invest-plus-api
    spec:
      containers:
        - name: scpi-invest-plus-api
          image: "{{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value:  "{{.Values.application.environment }}"
          envFrom:
            - secretRef:
                name: api-db-credentials
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2

      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-app-config
