apiVersion: apps/v1
kind: Deployment
metadata:
  name: scpi-invest-plus-api
  labels:
    app: scpi-invest-plus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scpi-invest-plus-api
  template:
    metadata:
      name: scpi-invest-plus-api
      labels:
        app: scpi-invest-plus-api
    spec:
      containers:
        - name: scpi-invest-plus-api
          image: "{{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value:  "{{.Values.application.environment }}"
            - name: ELASTICSEARCH_HOSTNAME
              value: "{{ .Values.elasticsearch.hostname }}"
          envFrom:
            - secretRef:
                name: scpi-invest-plus-api-secret