apiVersion: v1
kind: Service
metadata:
  name: kibana-batch
  labels:
    app: kibana-batch
spec:
  ports:
    - port: 80
      targetPort: 5601
      protocol: TCP
      name: http
  selector:
    app: kibana-batch
  type: ClusterIP